---
version: 0.2

phases:
  pre_build:
    commands:
      - echo 'pre_build.'
      - packer validate template.json
  build:
    commands:
      - echo 'build'
      - packer build template.json
  post_build:
    commands:
      - echo 'post_build'
