---
version: 0.2

env:
  variables:
    USER: root

phases:
  pre_build:
    commands:
      - echo 'pre_build.'
      - echo "http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
      - apk add jq aws-cli py-paramiko --update
      - packer validate template.json
  build:
    commands:
      - echo 'build'
      - curl -sqL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region ap-northeast-1
      - aws configure set aws_access_key_id `jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `jq -r '.Token' aws_credentials.json`
      - packer build template.json
  post_build:
    commands:
      - echo 'post_build'
